### ISSUE TITLE
Prevent initial state to get applied when a controller is attached

### ISSUE THREAD

**Issue by sbis04** [gskinner/flutter_animate#24]
Is there a way to prevent the initial state of any effect to get applied before it's triggered using the controller? In the following example, I don't want to show the container as faded to 0.5 initially:

```dart
Animate(
  controller: controller,
  adapter: adapter,
  effects: [
    FadeEffect(
      delay: 10.ms,
      duration: 1000.ms,
      begin: 0.5,
      end: 1.0,
    )
  ],
  child: Container(
    height: 100,
    width: 100,
    decoration: BoxDecoration(
      color: Colors.blueGrey,
      borderRadius: BorderRadius.circular(16),
    ),
  ),
)
```

The above example might not be a good use case, but I need to do it with some other animation effects.

**Comment by gskinner** [comment]
I can't think of an easy way to do that (other than not actually applying the `Animate` initially) — in fact, a bunch of work went into making sure that the initial state was applied properly to avoid flickering at the start of animations. :)

If you're able to provide me a real-world example, it would help me understand the use-case better.

**Comment by sbis04** [comment]
So, I basically wanted an effect where the **Fade** goes from `0.5` to `1.0` and then again goes back to `0.5`:

```dart
Animate(
  controller: controller,
  adapter: adapter,
  effects: [
    FadeEffect(
      curve: Curves.easeInOut,
      delay: 0.ms,
      duration: 1.seconds,
      begin: 0.5,
      end: 1,
    ),
    const ThenEffect(),
    FadeEffect(
      curve: Curves.easeInOut,
      delay: 1.seconds,
      duration: 1280.ms,
      begin: 1,
      end: 0.5,
    ),
  ],
  ...
)
```

But using this library I wasn't able to recreate this animation. I believe this is a very common usecase. Is it possible in a different way that I'm not aware of?

**Comment by gskinner** [comment]
Just to make sure I'm understanding... you want it to start at an opacity of 1.0, jump directly to an opacity of 0.5 when the animation is started, animate 0.5 -> 1.0 -> 0.5, then jump back to 1.0 when the animation ends?

**Comment by sbis04** [comment]
Let's go one-by-one, first just take the case that I want to start from 0.5 initially, and just animate 0.5 -> 1.0 -> 0.5, but this doesn't take me back to the initial 0.5 opacity state that I had. So, is it possible to go back to the initial opacity state?

**Comment by gskinner** [comment]
That actually should work. What won't work (and what you are probably running into) is the opposite — going 1.0 -> 0.5 -> 1.0.

The reason for this is because (as you know from this issue) the effects are persistent, so the first FadeEffect will continue to apply a 0.5 opacity when it ends, which then just gets nested with the second one.

You can work around this with `.swap`, which lets you basically rewrite the whole animation, but has its own limitations (ex. the new animation has its own controller). Here's a rough sketch (not tested):
```
foo.animate()
  .fade(begin: 1, end: 0.5)
  .then()
  .swap(builder: (_, o) => o.animate().fade(begin: 0.5, end: 1.0)
```

Docs for swap here:
https://pub.dev/documentation/flutter_animate/latest/effects_swap_effect/SwapEffect-class.html

The next version will make these kind of out-and-back animations easier with the addition of a `loop` extension for `AnimationController`, so you can just tell the controller to play forward and back once.
https://github.com/gskinner/flutter_animate/commit/42824b2e5601e1395d093d771f09657e60c39da4

**Comment by thesensibledev** [comment]
@sbis04 did you get a chance to look at Issue #11 ? We have discussed some ways of delaying the triggering and resetting the animation. Hope of the method works out for you.
