### ISSUE TITLE
Problems with adapter since switching to the latest git branch.

### ISSUE THREAD

**Issue by rienkkk** [gskinner/flutter_animate#65]
I have an animate widget that uses an `adapter` with an `ValueNotifierAdapter`, the `ValueNotifier` is being called lower in the widget tree for some actions.

The ValueNotifier
`ValueNotifier<double> notifier = ValueNotifier(0);`

The widget:
``` dart
Animate(
  effects: [
    FadeEffect(begin: 0.0, end: isDark(context) ? 0.2 : 0.7),
  ],
  adapter: ValueNotifierAdapter(notifier),
  child: ColoredBox(
    color: Theme.of(context).colorScheme.onBackground,
  ),
),
```

When this value is being called the following error presents itself:
``` dart
════════ Exception caught by foundation library ════════════════════════════════
The following _CastError was thrown while dispatching notifications for ValueNotifier<double>:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      Adapter.updateValue
adapter.dart:57
#1      ValueNotifierAdapter.attach.<anonymous closure>
value_notifier_adapter.dart:18
#2      ChangeNotifier.notifyListeners
change_notifier.dart:381
#3      ValueNotifier.value=
change_notifier.dart:495
#4      _CreateSheetWrapperState.build.<anonymous closure>.<anonymous closure>
create_sheet.dart:219
#5      ListenEffect.build.<anonymous closure>
listen_effect.dart:70
#6      AnimationLocalListenersMixin.notifyListeners
listener_helpers.dart:161
#7      AnimationController._tick
animation_controller.dart:837
#8      Ticker._tick
ticker.dart:249
#9      SchedulerBinding._invokeFrameCallback
binding.dart:1289
#10     SchedulerBinding.handleBeginFrame.<anonymous closure>
binding.dart:1140
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     SchedulerBinding.handleBeginFrame
binding.dart:1138
#13     SchedulerBinding._handleBeginFrame
binding.dart:1055
#14     _invoke1 (dart:ui/hooks.dart:164:13)
#15     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:316:5)
#16     _beginFrame (dart:ui/hooks.dart:101:31)
The ValueNotifier<double> sending notification was: ValueNotifier<double>#3b588(0.8651355504989624)
```

I also get a lot of null check operator errors:
`Null check operator used on a null value`

**Comment by gskinner** [comment]
I'm pretty sure that what's happening here is that the `ValueNotifierAdapter` is getting rebuilt, but the `ValueNotifier` it's isn't rebuilt — because they are managed in different Widgets. This creates an orphan `Adapter`, that's still subscribed to the notifier, but has been "detached", so it's controller is set to null. When the value updates, it notifies the orphan adapter, which tries to update the null controller, which errors.

I just pushed an update that I think will fix this by ensuring that adapters correctly unsubscribe when they are detached. Could you please test and let me know if it resolves your issue?

**Comment by rienkkk** [comment]
It is indeed solved now. Thanks for the quick response :)!

**Comment by gskinner** [comment]
Excellent!
